version: "2.1"

volumes:
  metricsdashboard_db:

networks:
  isolation-network:
    driver: bridge

services:
  server:
    container_name: server
    restart: always
    build: server/.
    ports:
      - "49162:4000"
    networks:
      - isolation-network
  app:
    container_name: app
    restart: always
    build: app/.
    ports:
      - "49161:8080"
    links:
      - server
    networks:
      - isolation-network